openapi: '3.0.2'

components:
  schemas:
    Boardgames:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          playerCount:
            type: integer
          description: 
            type: string
          rating:
            type: number
      example:
        - id: 1
          name: "catan"
          playerCount: 4
          description: "This in the OG of boardgames. Every boardgame after has stolen ideas from here"
          rating: 4.7  
info:
  title: boardgames
  description: This is a one stop to find all the latest games and old favorites. 
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /boardgames:
    get:
      summary: returns a list of boardgames
      responses:
        '200':
          description: returns a JSON array of boardgames
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/Boardgames'
        '400':
          description: The cake was a lie
    post:
      summary: Creates a boardgame
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Boardgames'
      responses:
        '201':
          description: Boardgame created
  /boardgames/{id}:
    get:
      summary: returns a particular boardgame
      parameters:
        - name: id
          in: path
          required: true
          description: the id of the boardgame to return
          schema:
            type: integer
            format: int64
            minimum: 1 
      responses:
        '200':
            description: a boardgame object
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 3141592
                    name: 
                      type: string
                      example: catan
                    playerCount:
                      type: integer
                      format: int64
                      example: 4
                    description: 
                      type: string
                      example: Resource biulding game to aquire victory points and destroy your friends
                    rating:
                      type: number
                      format: double
                      example: 4.7
        '400':
          description: the specified ID is invalid (not a number)
        '404':
          description: the boardgame with the specified ID was not found
        default:
          description: the cake is a lie
    patch:
      summary: 'Update a boardgame'
      parameters:
        - name: id
          in: path
          required: true
          description: the id of the boardgame to return
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Boardgames'
      responses:
        '201':
          description: Boardgame created
        '400':
          description: the specified ID is invalid (not a number)
        '404':
          description: the boardgame with the specified ID was not found
        default:
          description: the cake is a lie
    delete:
      summary: 'delete a boardgame'
      parameters:
        - name: id
          in: path
          required: true
          description: the id of the boardgame to return
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '201':
          description: Boardgame deleted
        '400':
          description: the specified ID is invalid (not a number)
        '404':
          description: the boardgame with the specified ID was not found
        default:
          description: the cake is a lie
